name: Android Build (Wrapper Included)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Generate Gradle Wrapper (7.4.2)
        run: gradle wrapper --gradle-version 7.4.2

      - name: Give gradlew permission
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MiniBrowser-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
